[package]
name = "pallet-did"
version = '2.0.0-rc3'
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
    'timestamp/std',
]

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.frame-support]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.system]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
package = 'frame-system'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.sp-std]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.timestamp]
git = 'https://github.com/paritytech/substrate.git'
default_features = false
package = 'pallet-timestamp'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'
